[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['chmod -R 775 storage']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'